# Default values for cla-frontend in a uat environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: "uat"
secretName: ~

envVars:
  BACKEND_BASE_URI:
    # Using service name instead of external domain name
    value: "http://cla-backend-app.laa-cla-backend-uat.svc.cluster.local"
  SESSION_COOKIE_NAME:
    value: "SID"
  SESSION_COOKIE_SECURE:
    value: "False"
  SESSION_COOKIE_HTTPONLY:
    value: "False"
  SESSION_COOKIE_SAMESITE:
    value: "None"
